INSERT INTO products (product_name, description, price, category, brand) VALUES 
('Herrenpullover Durant', 'Pullover aus 100% Baumwolle von Durant', 69.99, 'Pullover', 'Durant'),
('Tommy Hilfiger Hemd', 'Hochwertiges Hemd in der Farbe blau von Tommy Hilfiger', 79.95, 'Hemden', 'Tommy Hilfiger'),
('Pier One Businesshemd', 'Hemd von Pier One in weiß für den perfekten Business look', 25.49, 'Hemden', 'Pier One'),
('Mango SLIM FIT Hemd', 'Nachhaltigkeit wird bei Mango und diesem Hemd groß geschrieben', 49.99, 'Hemden', 'Mango'),
('Tom Tailor Denim Hemd', 'Hemd original von Tom Tailor.. betonung auf original :)', 29.99, 'Hemden', 'Tom Tailor'),
('Tommy Hilfiger Tailored SLIM FIT Businesshemd', 'Tommy Hilfger Hemd aus hochwertigen Stuff only for you', 55.95, 'Hemden', 'Tommy Hilfiger'),
('Kronstadt Dean Hemd mix colour', 'Dieses Hemd ist perfekt geeignet für den Auftritt als Clown', 64.95, 'Hemden', 'Kronstadt'),
('Farah Steen Hemd stellar', 'Farah Dean Hemden - be yourself be farah ', 62.95, 'Hemden', 'Farah'),
('Jack & Jones PREMIUM JPRBLAFRANCO SUIT SET - Anzug', 'Anzug von Jack&Jones erhätlich in medievel blue, black & dark navy', 99.99, 'Anzug', 'Jack&Jones'),
('JOOP! FINCH-BRAD - Anzug', 'Sehr schicker Anzug von JOOP! in blue und anthracite', 499.00, 'Anzug', 'JOOP!'),
('BOSS Anzug', 'Der Boss trägt den Anzug von BOSS in dark blue', 749.00, 'Anzug', 'BOSS'),
('BOSS Anzug', 'BOSS Anzug in der Farbe grau', 499.00, 'Anzug', 'BOSS'),
('Trenchcoat Victoria Beckham', 'Victoria Beckham Belted Trenchcoat Farbe taupe', 1650.00, 'Trenchcoat', 'Victoria Beckham'),
('Esprit Collection Trenchcoat', 'Trenchcoat  von Esprit Collection in der Farbe Sand', 139.99, 'Trenchcoat', 'Esprit'),
('Mango Trenchcoat', 'Trenchcoat von Mango in der Farbe marron moyen', 69.99, 'Trenchcoat', 'Mango'),
('Stradivarius Trenchcoat', 'Trenchcoat von Stradivarius in der Farbe stone', 38.98, 'Trenchcoat', 'Stradivarius'),
('Vila VIMOVEMENT-Trenchcoat', 'VIMOVEMENT-Trenchcoat von VIla in der Farbe beige', 38.49, 'Trenchcoat', 'Vila'),
('Cache Cache Trenchcoat', 'Trenchcoat von Cache Cache in der Farbe light brown', 39.90, 'Trenchcoat', 'Cache Cache'),
('Pimkie Trenchcoat', 'Trenchcoat von Pimkie in der Farbei beige', 35.99, 'Trenchcoat', 'Pimkie'),
('Desires Tessa - Trenchcoat', 'Trenchcoat von Desires in der Farbe Sand Typ TESSA', 39.95, 'Trenchcoat', 'Desires'),
('Vero Moda Petite VMCELESTE Trenchcoat', 'Trenchcoat von Vero Moda Petite Typ VMCELESTE', 39.99, 'Trenchcoat', 'Vero Moda Petite'),
('Vero Moda VMMADISON Trenchcoat', 'Trenchcoat von Vero Moda Petity Typ VMMADISON', 49.99, 'Trenchcoat', 'Vero Moda Petite'),
('Desires Trenchcoat', 'Trenchcoat von Desires in der Farbe dark blue', 66.95, 'Trenchcoat', 'Desires'),
('ONLY Petite Trenchcoat', 'Trenchcoat von ONLY Petite Farbe humus Typ ONLLINE', 44.99, 'Trenchcoat', 'ONLY Petite'),
('Lacoste Sneaker low', 'Sneaker low von Lacoste in der Farbe white', 89.95, 'Schuhe', 'Lacoste'),
('Skechers Sport Sneaker low', 'Sneaker low von Skechers Sport in der Farbe natural', 59.95, 'Schuhe', 'Skechers Sport'),
('adidas Sneaker low', 'Sneaker low von adidas Originals in der Farbe footwear white', 64.95, 'Schuhe', 'adidas'),
('Puma Sneaker low', 'Sneaker low von Puma in der Farbe white Typ CARINA', 44.99, 'Schuhe', 'Puma'),
('Nike Sneaker low', 'Sneaker von Nike Sportswear in der Farbe white Typ INTERNATIONALIST', 76.00, 'Schuhe', 'Nike'),
('New Balance Sneaker low', 'Sneaker low von New Balance in der Farbe blue navy Typ GW500', 60.00, 'Schuhe', 'New Balance'),
('Skechers Sport Sneaker low', 'Sneaker low von Skechers Sport in der Farbe taupe Typ OG85', 41.95, 'Schuhe', 'Skechers Sport'),
('Vans Sneaker low', 'Sneaker low von VANS in der Farbe baby blue Typ OLD SKOOL', 79.95, 'Schuhe', 'Vans'),
('Geox Sneaker low', 'Sneaker low von Geox in der Farbe light gold Typ BLOMIEE', 71.56, 'Schuhe', 'Geox'),
('Veja Sneaker low', 'Sneaker low von Veja in der Farbe extra white Typ V-10', 124.95, 'Schuhe', 'Veja');
